import type { Metadata } from "next"
import { LegalPage } from "@/components/legal-page"

export const metadata: Metadata = {
  title: "Privacy Policy | Orbit LM",
  description: "How Orbit-LM handles account, workspace, billing and connected Google service information.",
  alternates: { canonical: "https://orbit-lm.com/privacy-policy" },
}

export default function PrivacyPolicy() {
  return <LegalPage title="Privacy Policy" intro="This policy explains how Orbit-LM handles information when you visit orbit-lm.com, use your workspace, or contact our team." sections={[
    { title: "Who to contact", content: <p>Orbit-LM provides this service. For privacy questions, access requests or deletion requests, email <a href="mailto:tsblsestudio@gmail.com">tsblsestudio@gmail.com</a>. When an organization manages your workspace, it also determines how the client and team information it uploads is used; you may need to contact that organization.</p> },
    { title: "Information we handle", content: <><p>We handle account and profile details, such as your name, email, password credentials and preferences; records you add about clients, leads, projects, tasks, expenses, groceries, investments, savings and invoices; uploaded logos; optional food, calorie and health-tracking entries; and messages you send to support.</p><p>We also handle subscription identifiers and payment status from checkout providers, connection credentials for services you authorize, and technical information such as IP addresses, browser details and request/error logs used to operate and secure the service. Payment card details are entered with the checkout provider rather than in Orbit’s workspace forms.</p></> },
    { title: "Why we use information", content: <p>We use information to provide your workspace, authenticate access, apply plan permissions, save and display your records, generate reports, operate billing reminders and invoice emails, respond to support requests, prevent abuse and diagnose problems. Where applicable law requires a legal basis, these purposes rely on performing our agreement with you, legitimate interests in operating a secure service, legal obligations, or consent for optional processing. If you choose not to provide required account information, we may be unable to provide the account.</p> },
    { title: "Optional Google connections", content: <><p>Google connections are optional. With your permission, Orbit can access and manage calendar events and send emails through Gmail for features you request. We store the tokens needed to maintain those connections and process the event details, recipients and message content needed to perform the action. The current Gmail connection requests sending access, not general inbox-reading access.</p><p>Google user data is used for these connected features, not advertising, sale to data brokers or general-purpose AI model training. Orbit-LM’s use and transfer of information received from Google APIs follows the <a href="https://developers.google.com/terms/api-services-user-data-policy">Google API Services User Data Policy</a>, including its Limited Use requirements. You can revoke access in your <a href="https://myaccount.google.com/connections">Google account connections</a>. Revocation stops future authorized access but does not automatically erase records already saved in Orbit; contact us to request deletion.</p></> },
    { title: "Sharing and service providers", content: <p>Information is shared with people you authorize in your workspace and with recipients of messages or invoices you send or schedule. Service providers support hosting, storage, email delivery and checkout, including Vercel, Supabase, Resend, and Hotmart where used. Google processes information when you connect its services. Providers receive information needed for their roles and may have their own privacy terms. We may also disclose information when required by law or necessary to protect against fraud or security threats. We do not sell workspace records.</p> },
    { title: "Cookies and local storage", content: <p>Orbit uses session cookies to keep you signed in and browser storage to remember preferences such as theme and currency. You can clear these through your browser, which may sign you out or reset preferences. Hosting infrastructure also processes technical logs. These controls are separate from permissions you grant to connected services.</p> },
    { title: "Retention and deletion", content: <p>We retain information while needed to provide the service and for relevant security, accounting or legal purposes. Records deleted through a supported archive flow remain recoverable for three months before scheduled permanent deletion; ordinary archived records may remain until you remove them. Where offered, permanent deletion removes records sooner. This archive period does not apply uniformly to every account, message, backup or provider log. Backups and records required for legitimate legal purposes may remain longer. Contact us for account-wide deletion; we may verify your identity before acting.</p> },
    { title: "Your choices and rights", content: <p>You can edit available profile and workspace fields, use available export and deletion tools, and disconnect optional integrations. Depending on your location, you may have rights to access, correct, delete or obtain a copy of personal information, restrict or object to processing, withdraw consent, and complain to a data protection authority. Email our privacy contact to exercise these rights. Withdrawing consent does not affect processing already lawfully performed.</p> },
    { title: "Security and international processing", content: <p>We use technical access controls and encrypted transport, but no online service can guarantee absolute security. Keep your password private and grant workspace access carefully. Providers may process information outside your country, where laws may differ. Where required, international transfers must use applicable legal safeguards; contact us for information about the arrangements relevant to your request.</p> },
    { title: "Children and policy changes", content: <p>Orbit is not designed for children. If you believe a child has provided personal information without appropriate authorization, contact us. We may update this policy as the service changes, update the date above, and provide additional notice or request consent where required. Contact <a href="mailto:tsblsestudio@gmail.com">tsblsestudio@gmail.com</a> with any questions.</p> },
  ]}/>
}
