"use client"
import { useEffect, useState } from "react"

export function AdminHealth() {
  const [data, setData] = useState<any>(null)
  useEffect(() => { fetch("/api/admin/health", { cache: "no-store" }).then(r => r.json()).then(setData).catch(() => setData({ error: "Health information is unavailable." })) }, [])
  const events = data?.events || []
  return <main className="min-h-screen bg-[#050812] p-6 text-white"><section className="mx-auto max-w-5xl rounded-3xl border border-cyan-300/25 bg-[#0a1422] p-6 shadow-2xl"><a href="/dashboard" className="text-sm text-cyan-200 hover:underline">← Back to Orbit</a><div className="mt-5 flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-200">Orbit administration</p><h1 className="mt-2 text-3xl font-semibold">Automation health</h1><p className="mt-2 text-sm text-slate-400">Recent invoice, scheduled-job and Hotmart events. Errors are retained here for review.</p></div><span className={`rounded-full px-3 py-1 text-sm ${data?.summary?.healthy ? "bg-emerald-400/15 text-emerald-200" : "bg-red-400/15 text-red-200"}`}>{data?.summary?.healthy ? "Healthy" : "Needs review"}</span></div><div className="mt-7 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/[.04] text-slate-400"><tr><th className="p-3">Time</th><th className="p-3">Area</th><th className="p-3">Result</th><th className="p-3">Details</th></tr></thead><tbody>{events.map((event: any) => <tr key={event.id} className="border-t border-white/5"><td className="p-3 text-slate-400">{new Date(event.occurred_at).toLocaleString()}</td><td className="p-3">{event.source}</td><td className="p-3"><span className={event.severity === "error" ? "text-red-300" : event.severity === "warning" ? "text-amber-200" : "text-emerald-200"}>{event.event_type}</span></td><td className="p-3 text-slate-300">{event.message}</td></tr>)}</tbody></table>{!events.length && <p className="p-6 text-sm text-slate-400">No operational events have been recorded yet.</p>}</div></section></main>
}
