"use client"
import {FormEvent,useEffect,useMemo,useState} from "react"
import {Activity,Coins,PiggyBank,ShoppingBasket,Target,Trash2,WalletCards} from "lucide-react"
import {toast} from "sonner"
import {Card} from "@/components/ui/card"
import {Button} from "@/components/ui/button"
import {Input} from "@/components/ui/input"
type R=Record<string,any>
const money=(n:number,c:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency:c||"USD"}).format(n||0)

export function PersonalHub({expenses,groceries,currency}:R){
 const [entries,setEntries]=useState<R[]>([]);useEffect(()=>{fetch("/api/data/food_entries").then(r=>r.json()).then(d=>setEntries(d.items||[])).catch(()=>{})},[])
 const month=new Date().toISOString().slice(0,7),today=new Date().toISOString().slice(0,10)
 const expenseTotal=expenses.filter((x:R)=>String(x.expense_date||x.created_at).slice(0,7)===month).reduce((n:number,x:R)=>n+Number(x.amount||0),0)
 const groceryTotal=groceries.filter((x:R)=>String(x.purchased_at||x.created_at).slice(0,7)===month).reduce((n:number,x:R)=>n+Number(x.actual_cost||x.estimated_cost||0),0)
 const calories=entries.filter(x=>String(x.consumed_at).slice(0,10)===today).reduce((n,x)=>n+Number(x.calories||0),0)
 return <div className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><HubMetric icon={Activity} label="Calories today" value={`${Math.round(calories)} kcal`} color="cyan"/><HubMetric icon={WalletCards} label="Monthly expenses" value={money(expenseTotal,currency)} color="violet"/><HubMetric icon={ShoppingBasket} label="Monthly groceries" value={money(groceryTotal,currency)} color="emerald"/></div><Card className="border-cyan-300/15 bg-gradient-to-br from-cyan-300/[.08] to-violet-400/[.06] p-6 text-white"><h2 className="text-xl font-semibold">Your personal rhythm</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Health, household spending and groceries now live in one calm workspace. Open a section under Personal to record details; this dashboard keeps the month’s essentials visible.</p></Card></div>
}

export function InvestmentsHub({holdings,currency}:R){
 const [goals,setGoals]=useState<R[]>([]);useEffect(()=>{load()},[]);async function load(){const r=await fetch("/api/data/savings_goals"),d=await r.json();if(r.ok)setGoals(d.items||[])}
 const totals=useMemo(()=>holdings.reduce((a:R,x:R)=>{const k=String(x.asset_type||"Stock");a[k]=(a[k]||0)+Number(x.quantity||0)*Number(x.current_price||x.buy_price||0);return a},{Stock:0,Crypto:0}),[holdings])
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=Object.fromEntries(new FormData(form)),r=await fetch("/api/data/savings_goals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...d,currency,target_amount:Number(d.target_amount),current_amount:Number(d.current_amount||0)})}),j=await r.json();if(!r.ok)return toast.error(j.error||"We could not create this goal.");setGoals(v=>[...(j.items||[]),...v]);form.reset();toast.success("Savings goal created.")}
 async function contribute(goal:R,amount:number){if(amount<=0)return;const next=Number(goal.current_amount||0)+amount,r=await fetch("/api/data/savings_goals",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:goal.id,current_amount:next})}),d=await r.json();if(!r.ok)return toast.error(d.error||"We could not update this goal.");setGoals(v=>v.map(x=>x.id===goal.id?d.items[0]:x))}
 async function remove(id:string){const r=await fetch("/api/data/savings_goals",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(!r.ok)return toast.error("We could not delete this goal.");setGoals(v=>v.filter(x=>x.id!==id))}
 return <div className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><HubMetric icon={Coins} label="Stocks market value" value={money(totals.Stock,currency)} color="cyan"/><HubMetric icon={Coins} label="Crypto market value" value={money(totals.Crypto,currency)} color="violet"/><HubMetric icon={PiggyBank} label="Saved toward goals" value={money(goals.reduce((n,x)=>n+Number(x.current_amount||0),0),currency)} color="emerald"/></div><Card className="border-cyan-300/20 bg-white/5 p-5 text-white"><details open><summary className="cursor-pointer text-lg font-semibold">Create a savings goal</summary><form onSubmit={add} className="mt-4 grid gap-3 sm:grid-cols-4"><Input name="name" required placeholder="Goal name"/><Input name="target_amount" required min="0.01" step="0.01" type="number" placeholder={`Target (${currency})`}/><Input name="current_amount" min="0" step="0.01" type="number" placeholder="Already saved"/><Input name="target_date" type="date"/><Button className="sm:col-span-4 bg-cyan-300 text-slate-950">Add savings goal</Button></form></details></Card><div className="grid gap-4 lg:grid-cols-2">{goals.map(goal=><Goal key={goal.id} goal={goal} currency={currency} contribute={contribute} remove={remove}/>)}{!goals.length&&<Card className="border-dashed border-white/15 bg-white/[.03] p-8 text-center text-slate-400"><Target className="mx-auto mb-3 text-cyan-300"/>Create your first savings goal to track progress here.</Card>}</div></div>
}
function Goal({goal,currency,contribute,remove}:R){const [amount,setAmount]=useState(""),pct=Math.min(100,Number(goal.current_amount||0)/Number(goal.target_amount||1)*100);return <Card className="border-white/10 bg-white/5 p-5 text-white"><div className="flex justify-between"><div><h3 className="font-semibold">{goal.name}</h3><p className="text-xs text-slate-500">{goal.target_date?`Target date ${new Date(goal.target_date+"T00:00:00").toLocaleDateString()}`:"No target date"}</p></div><Button variant="ghost" size="icon" onClick={()=>remove(goal.id)} aria-label={`Delete ${goal.name}`}><Trash2 size={16}/></Button></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-violet-400" style={{width:`${pct}%`}}/></div><div className="mt-2 flex justify-between text-sm"><b>{money(goal.current_amount,currency)}</b><span className="text-slate-400">of {money(goal.target_amount,currency)}</span></div><div className="mt-4 flex gap-2"><Input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0.01" step="0.01" placeholder="Add amount"/><Button onClick={()=>{contribute(goal,Number(amount));setAmount("")}} className="bg-cyan-300 text-slate-950">Save</Button></div></Card>}
function HubMetric({icon:I,label,value,color}:R){const style=color==="violet"?"border-violet-300/20 bg-violet-300/[.06]":color==="emerald"?"border-emerald-300/20 bg-emerald-300/[.06]":"border-cyan-300/20 bg-cyan-300/[.06]";return <Card className={`${style} p-5 text-white`}><I className="mb-4 text-cyan-300"/><span className="text-sm text-slate-400">{label}</span><b className="mt-1 block text-2xl">{value}</b></Card>}
