"use client"
import{useEffect,useMemo,useState}from"react"
import{useRouter}from"next/navigation"
import{Button}from"@/components/ui/button"
import{Input}from"@/components/ui/input"
import{Card}from"@/components/ui/card"
import{Badge}from"@/components/ui/badge"
import{toast}from"sonner"
import{BarChart3,Bitcoin,CheckCircle2,ClipboardList,DollarSign,FolderKanban,Globe2,LayoutDashboard,LogOut,Menu,Plus,Search,Settings,TrendingUp,Users,WalletCards,X}from"lucide-react"
type Rec=Record<string,any>
const nav=[["Overview",LayoutDashboard],["Leads",Globe2],["Pipeline",TrendingUp],["Projects",FolderKanban],["Tasks",ClipboardList],["Portfolio",WalletCards],["Reports",BarChart3],["Settings",Settings]] as const
export function OperationsDashboard(){
 const router=useRouter(),[page,setPage]=useState("Overview"),[mobile,setMobile]=useState(false),[query,setQuery]=useState("")
 const[leads,setLeads]=useState<Rec[]>([]),[tasks,setTasks]=useState<Rec[]>([]),[projects,setProjects]=useState<Rec[]>([]),[assets,setAssets]=useState<Rec[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{Promise.all(["leads","tasks","projects","assets"].map(load)).then(([l,t,p,a])=>{setLeads(l);setTasks(t);setProjects(p);setAssets(a)}).catch(e=>toast.error(e.message)).finally(()=>setLoading(false))},[])
 async function load(r:string){const x=await fetch("/api/data/"+r),d=await x.json();if(!x.ok)throw Error(d.error||"Could not load "+r);return d.items||[]}
 async function add(r:string,item:Rec,setter:any){const x=await fetch("/api/data/"+r,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(item)}),d=await x.json();if(!x.ok)return toast.error(d.error||"Save failed");setter((v:Rec[])=>[...(d.items||[]),...v]);toast.success("Saved")}
 async function edit(r:string,id:string,changes:Rec,setter:any){setter((v:Rec[])=>v.map(x=>x.id===id?{...x,...changes}:x));const x=await fetch("/api/data/"+r,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...changes})});if(!x.ok)toast.error("Update failed")}
 async function del(r:string,id:string,setter:any){setter((v:Rec[])=>v.filter(x=>x.id!==id));const x=await fetch("/api/data/"+r,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(!x.ok)toast.error("Delete failed")}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/")}
 const filtered=useMemo(()=>leads.filter(l=>JSON.stringify(l).toLowerCase().includes(query.toLowerCase())),[leads,query])
 const pipeline=leads.reduce((s,l)=>s+Number(l.estimated_value||0),0),portfolio=assets.reduce((s,a)=>s+Number(a.quantity||0)*Number(a.current_price||0),0)
 return <main className="min-h-screen bg-[#060910] text-white"><div className="fixed inset-0 bg-[radial-gradient(circle_at_10%_0%,rgba(8,145,178,.25),transparent_35%),radial-gradient(circle_at_90%_20%,rgba(124,58,237,.18),transparent_35%)]"/><div className="relative flex gap-4 p-3 lg:p-5">
 <aside className={(mobile?"flex":"hidden")+" fixed inset-3 z-50 w-64 flex-col rounded-3xl border border-white/10 bg-[#09111e]/95 p-4 backdrop-blur-xl lg:sticky lg:top-5 lg:flex lg:h-[calc(100vh-40px)]"}><div className="mb-7 flex items-center justify-between"><div><b>Orbit CRM</b><p className="text-xs text-slate-500">Business operating system</p></div><button className="lg:hidden" onClick={()=>setMobile(false)}><X/></button></div><nav className="space-y-1">{nav.map(([label,Icon])=><button key={label} onClick={()=>{setPage(label);setMobile(false)}} className={"flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm "+(page===label?"bg-cyan-300 text-slate-950":"text-slate-400 hover:bg-white/5")}><Icon size={17}/>{label}</button>)}</nav><div className="mt-auto rounded-xl border border-emerald-300/20 bg-emerald-300/5 p-3 text-xs text-slate-400"><b className="text-emerald-300">Supabase connected</b><p>Records sync securely across devices.</p></div><Button variant="ghost" onClick={logout} className="mt-2 justify-start text-slate-400"><LogOut size={16}/>Sign out</Button></aside>
 <section className="min-w-0 flex-1"><header className="mb-4 flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-3"><button onClick={()=>setMobile(true)} className="lg:hidden"><Menu/></button><div><h1 className="text-xl font-semibold">{page}</h1><p className="text-xs text-slate-500">{loading?"Loading workspace…":"Manage leads, delivery, tasks and capital."}</p></div></div><div className="relative hidden sm:block"><Search className="absolute left-3 top-2.5 text-slate-500" size={16}/><Input value={query} onChange={e=>setQuery(e.target.value)} className="w-72 border-white/10 bg-black/20 pl-9" placeholder="Search workspace"/></div></header>
 {page==="Overview"&&<Overview leads={leads} tasks={tasks} projects={projects} pipeline={pipeline} portfolio={portfolio}/>}
 {page==="Leads"&&<Leads items={filtered} addItem={(x:Rec)=>add("leads",x,setLeads)} editItem={(id:string,x:Rec)=>edit("leads",id,x,setLeads)} deleteItem={(id:string)=>del("leads",id,setLeads)}/>}
 {page==="Pipeline"&&<Pipeline items={leads} move={(id:string,status:string)=>edit("leads",id,{status},setLeads)}/>}
 {page==="Projects"&&<Projects items={projects} addItem={(x:Rec)=>add("projects",x,setProjects)} editItem={(id:string,x:Rec)=>edit("projects",id,x,setProjects)}/>}
 {page==="Tasks"&&<Tasks items={tasks} addItem={(x:Rec)=>add("tasks",x,setTasks)} editItem={(id:string,x:Rec)=>edit("tasks",id,x,setTasks)} deleteItem={(id:string)=>del("tasks",id,setTasks)}/>}
 {page==="Portfolio"&&<Portfolio items={assets} addItem={(x:Rec)=>add("assets",x,setAssets)} deleteItem={(id:string)=>del("assets",id,setAssets)}/>}
 {page==="Reports"&&<Reports leads={leads} projects={projects} pipeline={pipeline}/>}
 {page==="Settings"&&<SettingsView/>}
 </section></div></main>
}
function Metric({title,value,sub,Icon}:Rec){return <Card className="border-white/10 bg-white/5 p-5 text-white"><div className="flex justify-between text-sm text-slate-400">{title}<Icon size={18}/></div><b className="mt-4 block text-2xl">{value}</b><span className="text-xs text-emerald-300">{sub}</span></Card>}
function Panel({title,children}:Rec){return <Card className="border-white/10 bg-white/5 p-5 text-white"><h2 className="mb-4 font-semibold">{title}</h2><div className="space-y-2">{children}</div></Card>}
function Row({title,sub,badge,children}:Rec){return <div className="flex items-center justify-between gap-3 rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="min-w-0"><b className="block truncate text-sm">{title}</b><p className="truncate text-xs text-slate-500">{sub}</p></div><div className="flex items-center gap-2"><Badge className="bg-white/10">{badge}</Badge>{children}</div></div>}
function Overview({leads,tasks,projects,pipeline,portfolio}:Rec){return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Leads" value={leads.length} sub={leads.filter((x:Rec)=>x.status==="New").length+" new"} Icon={Users}/><Metric title="Pipeline" value={usd(pipeline)} sub="Potential revenue" Icon={DollarSign}/><Metric title="Projects" value={projects.length} sub="Video + websites" Icon={FolderKanban}/><Metric title="Portfolio" value={usd(portfolio)} sub="Tracked value" Icon={Bitcoin}/></div><div className="grid gap-4 xl:grid-cols-2"><Panel title="Priority follow-ups">{tasks.filter((t:Rec)=>t.status!=="Done").slice(0,6).map((t:Rec)=><Row key={t.id} title={t.title} sub={t.due_date||"No due date"} badge={t.priority}/>)}</Panel><Panel title="Delivery status">{projects.map((p:Rec)=><div key={p.id} className="rounded-xl bg-black/20 p-3"><div className="flex justify-between text-sm"><b>{p.name}</b><span>{p.progress}%</span></div><div className="mt-2 h-2 rounded bg-white/10"><div className="h-2 rounded bg-cyan-300" style={{width:String(p.progress)+"%"}}/></div></div>)}</Panel></div></div>}
function Form({fields,onSubmit,label="Save"}:Rec){return <Card className="border-white/10 bg-white/5 p-4 text-white"><form className="grid gap-3 md:grid-cols-3" onSubmit={e=>{e.preventDefault();onSubmit(Object.fromEntries(new FormData(e.currentTarget)));e.currentTarget.reset()}}>{fields.map((f:string)=><Input key={f} name={f} required={["company","name","title","symbol"].includes(f)} type={["estimated_value","budget","progress","quantity","buy_price","current_price"].includes(f)?"number":"text"} placeholder={f.replaceAll("_"," ")}/>) }<Button className="bg-cyan-300 text-slate-950">{label}</Button></form></Card>}
function Leads({items,addItem,editItem,deleteItem}:Rec){const[open,setOpen]=useState(false);return <div className="space-y-4"><div className="flex justify-between"><p className="text-sm text-slate-400">{items.length} opportunities</p><Button onClick={()=>setOpen(!open)} className="bg-cyan-300 text-slate-950"><Plus size={16}/>New lead</Button></div>{open&&<Form fields={["company","contact_name","email","phone","city","country","service","estimated_value"]} onSubmit={(x:Rec)=>{addItem({...x,status:"New",source:"Manual",estimated_value:Number(x.estimated_value||0)});setOpen(false)}}/>}<Panel title="Lead directory">{items.map((l:Rec)=><Row key={l.id} title={l.company} sub={(l.city||"")+" "+(l.country||"")+" · "+(l.service||"Both")} badge={usd(l.estimated_value)}><select value={l.status} onChange={e=>editItem(l.id,{status:e.target.value})} className="rounded bg-slate-800 p-1 text-xs">{["New","Contacted","Qualified","Proposal","Won","Lost"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>deleteItem(l.id)} className="text-xs text-red-300">Delete</button></Row>)}</Panel></div>}
function Pipeline({items,move}:Rec){const stages=["New","Contacted","Qualified","Proposal","Won"];return <div className="grid gap-3 xl:grid-cols-5">{stages.map(s=><Panel key={s} title={s+" ("+items.filter((x:Rec)=>x.status===s).length+")"}>{items.filter((x:Rec)=>x.status===s).map((l:Rec)=><div key={l.id} className="rounded-xl bg-black/20 p-3"><b className="text-sm">{l.company}</b><p className="text-xs text-slate-500">{usd(l.estimated_value)}</p><select value={l.status} onChange={e=>move(l.id,e.target.value)} className="mt-3 w-full rounded bg-slate-800 p-1 text-xs">{stages.map(x=><option key={x}>{x}</option>)}</select></div>)}</Panel>)}</div>}
function Projects({items,addItem,editItem}:Rec){const[open,setOpen]=useState(false);return <div className="space-y-4"><Button onClick={()=>setOpen(!open)} className="bg-cyan-300 text-slate-950"><Plus size={16}/>New project</Button>{open&&<Form fields={["name","client","kind","stage","deadline","budget","progress"]} onSubmit={(x:Rec)=>{addItem({...x,budget:Number(x.budget||0),progress:Number(x.progress||0)});setOpen(false)}}/>}<div className="grid gap-3 lg:grid-cols-2">{items.map((p:Rec)=><Panel key={p.id} title={p.name}><Row title={p.client} sub={(p.kind||"Project")+" · "+(p.stage||"Brief")} badge={usd(p.budget)}/><div className="h-2 rounded bg-white/10"><div className="h-2 rounded bg-violet-400" style={{width:String(p.progress)+"%"}}/></div><Input type="range" min="0" max="100" value={p.progress||0} onChange={e=>editItem(p.id,{progress:Number(e.target.value)})}/></Panel>)}</div></div>}
function Tasks({items,addItem,editItem,deleteItem}:Rec){const[title,setTitle]=useState("");return <div className="space-y-4"><div className="flex gap-2"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="New follow-up or task"/><Button onClick={()=>{if(title){addItem({title,priority:"Medium",status:"Open"});setTitle("")}}}>Add task</Button></div><Panel title="Follow-ups and reminders">{items.map((t:Rec)=><Row key={t.id} title={t.title} sub={t.due_date||"No due date"} badge={t.priority}><button onClick={()=>editItem(t.id,{status:t.status==="Done"?"Open":"Done"})} className={t.status==="Done"?"text-emerald-300":"text-slate-400"}><CheckCircle2 size={20}/></button><button onClick={()=>deleteItem(t.id)} className="text-xs text-red-300">Delete</button></Row>)}</Panel></div>}
function Portfolio({items,addItem,deleteItem}:Rec){const[open,setOpen]=useState(false),value=items.reduce((s:number,a:Rec)=>s+Number(a.quantity)*Number(a.current_price),0),cost=items.reduce((s:number,a:Rec)=>s+Number(a.quantity)*Number(a.buy_price),0);return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Metric title="Market value" value={usd(value)} sub="Current prices" Icon={WalletCards}/><Metric title="Cost basis" value={usd(cost)} sub="Recorded purchases" Icon={DollarSign}/><Metric title="Return" value={usd(value-cost)} sub={(cost?((value-cost)/cost*100).toFixed(1):"0")+"%"} Icon={TrendingUp}/></div><Button onClick={()=>setOpen(!open)}>Record purchase</Button>{open&&<Form fields={["symbol","name","asset_type","quantity","buy_price","current_price"]} onSubmit={(x:Rec)=>{addItem({...x,quantity:Number(x.quantity),buy_price:Number(x.buy_price),current_price:Number(x.current_price)});setOpen(false)}}/>}<Panel title="Stocks and crypto">{items.map((a:Rec)=><Row key={a.id} title={a.symbol+" · "+a.name} sub={a.quantity+" units · "+a.asset_type} badge={usd(a.quantity*a.current_price)}><button onClick={()=>deleteItem(a.id)} className="text-xs text-red-300">Delete</button></Row>)}</Panel></div>}
function Reports({leads,projects,pipeline}:Rec){const won=leads.filter((l:Rec)=>l.status==="Won"),conversion=leads.length?won.length/leads.length*100:0;return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Metric title="Conversion" value={conversion.toFixed(1)+"%"} sub={won.length+" won deals"} Icon={BarChart3}/><Metric title="Pipeline" value={usd(pipeline)} sub="All opportunities" Icon={TrendingUp}/><Metric title="Delivery value" value={usd(projects.reduce((s:number,p:Rec)=>s+Number(p.budget),0))} sub="Project budgets" Icon={FolderKanban}/></div><Panel title="Pipeline by stage">{["New","Contacted","Qualified","Proposal","Won"].map(s=><Row key={s} title={s} sub={leads.filter((l:Rec)=>l.status===s).length+" leads"} badge={usd(leads.filter((l:Rec)=>l.status===s).reduce((n:number,l:Rec)=>n+Number(l.estimated_value),0))}/>)}</Panel></div>}
function SettingsView(){return <div className="grid gap-4 lg:grid-cols-2"><Panel title="Data and security"><p className="text-sm text-slate-400">Supabase persistence is active behind authenticated server routes. Your service key is never sent to the browser.</p></Panel><Panel title="Google lead finder"><p className="text-sm text-slate-400">Use the existing Google Places integration to discover businesses without listed websites. API usage remains subject to your Google quota.</p></Panel><Panel title="Responsible outreach"><p className="text-sm text-slate-400">Personalize every message and comply with local privacy, anti-spam and platform rules. Airbnb scraping is intentionally excluded.</p></Panel></div>}
function usd(n:any){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(n||0))}

