"use client"
import{useEffect,useState}from"react";import{Card}from"@/components/ui/card";import{Button}from"@/components/ui/button";import{CalendarDays,Coins,TrendingUp,WalletCards}from"lucide-react";import{Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis}from"recharts";import{monthSeries}from"@/components/history-calendar";type R=Record<string,any>;
export function OverviewV3({tasks,groceries,leads,expenses,holdings,projects,addTask,editTask,language="en",currency="USD"}:R){const[data,setData]=useState<R>({events:[]}),[text,setText]=useState("");useEffect(()=>{fetch("/api/calendar/events").then(r=>r.json()).then(setData).catch(()=>{})},[]);const money=(n:any,d=0)=>new Intl.NumberFormat(locale(language),{style:"currency",currency,maximumFractionDigits:d}).format(Number(n||0)),months=monthSeries(6,expenses,leads,projects,holdings,groceries),cur=months.at(-1)||{},prev=months.at(-2)||{},net=Number(cur.income||0)-Number(cur.expenses||0),prevNet=Number(prev.income||0)-Number(prev.expenses||0),invested=holdings.reduce((n:number,x:R)=>n+Number(x.quantity||0)*Number(x.current_price||0),0),pipeline=leads.reduce((n:number,x:R)=>n+Number(x.estimated_value||0),0);return <div className="space-y-4">
 <div className="grid gap-4 xl:grid-cols-2"><Panel title="Today Focus"><div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} className="h-9 flex-1 rounded-md border border-cyan-300/20 bg-black/20 px-3 text-sm outline-none focus:ring-2 focus:ring-cyan-300" placeholder="Write a new focus…"/><Button onClick={()=>{if(text.trim()){addTask({title:text.trim(),kind:"Task",priority:"High",status:"Open",notes:""});setText("")}}}>Add</Button></div>{tasks.filter((x:R)=>x.kind!=="Follow-up"&&x.status!=="Done").slice(0,8).map((x:R)=><div key={x.id} className="flex justify-between rounded-xl bg-black/20 p-3"><button className="text-left" onClick={()=>{const title=prompt("Edit focus",x.title);if(title)editTask(x.id,{title})}}><b className="text-sm">{x.title}</b><p className="text-xs text-slate-500">{x.notes||"Click title to edit"}</p></button><button onClick={()=>editTask(x.id,{status:"Done"})} className="text-emerald-300">✓</button></div>)}</Panel><Panel title="My Calendar · next occasions">{!data.connected?<Button asChild><a href="/api/calendar/connect"><CalendarDays size={16}/>Connect Google Calendar</a></Button>:(data.events||[]).slice(0,6).map((x:R)=><a key={x.id} href={x.link} target="_blank" className="block rounded-xl border border-violet-400/15 bg-violet-400/5 p-3"><p className="text-xs text-cyan-300">{new Date(x.start).toLocaleString(locale(language))}</p><b className="text-sm">{x.title}</b></a>)}</Panel></div>
 <div className="grid gap-3 sm:grid-cols-3"><Metric title="Sales pipeline" value={money(pipeline)} sub="Potential revenue" icon={TrendingUp}/><Metric title="Spending" value={money(cur.expenses)} sub="This month" icon={WalletCards}/><Metric title="Investments" value={money(invested)} sub="Current value" icon={Coins}/></div>
 <div className="grid gap-4 xl:grid-cols-2"><Card className={"border p-5 text-white "+(net>=0?"border-emerald-400/30 bg-emerald-400/10":"border-red-400/30 bg-red-400/10")}><p className="text-sm">This month result</p><b className={"mt-3 block text-3xl "+(net>=0?"text-emerald-300":"text-red-300")}>{money(net)}</b><p className="mt-2 text-xs">Income {money(cur.income)} · Expenses {money(cur.expenses)}</p></Card><Card className="border-cyan-400/30 bg-cyan-400/10 p-5 text-white"><p className="text-sm">Last month result</p><b className="mt-3 block text-3xl">{money(prevNet)}</b><p className="mt-2 text-xs">Change {money(net-prevNet)}</p></Card></div>
 <Panel title="Six-month financial pulse"><div className="h-56"><ResponsiveContainer><AreaChart data={months}><CartesianGrid stroke="#ffffff12"/><XAxis dataKey="label" stroke="#64748b"/><YAxis stroke="#64748b"/><Tooltip contentStyle={{background:"#0b1320",border:"1px solid #ffffff20"}}/><Area dataKey="income" stroke="#34d399" fill="#34d39933"/><Area dataKey="expenses" stroke="#fb7185" fill="#fb718533"/></AreaChart></ResponsiveContainer></div></Panel>
 </div>}
function Metric({title,value,sub,icon:I}:R){return <Card className="border-white/10 bg-white/5 p-5 text-white"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">{title}</p><b className="mt-3 block text-2xl">{value}</b><span className="text-xs text-cyan-300">{sub}</span></div>{I&&<div className="rounded-xl bg-cyan-300/10 p-2 text-cyan-300"><I size={18}/></div>}</div></Card>}
function Panel({title,children}:R){return <Card className="border-white/10 bg-white/5 p-5 text-white"><h2 className="mb-4 font-semibold">{title}</h2><div className="space-y-2">{children}</div></Card>}function locale(x:string){return({pt:"pt-BR",es:"es-ES",de:"de-DE",fr:"fr-FR",it:"it-IT",nl:"nl-NL",ja:"ja-JP",ko:"ko-KR"}as R)[x]||"en-US"}
