"use client"
import { useEffect } from "react"
type D=Record<string,string>
const dictionaries:Record<string,D>={
pt:{"Overview":"Visão geral","Clients":"Clientes","Leads Management":"Gestão de leads","Tasks & Follow-ups":"Tarefas e acompanhamentos","Calendar":"Calendário","Pipeline":"Funil de vendas","Projects":"Projetos","Groceries":"Supermercado","Expenses":"Despesas","Stocks":"Ações","Crypto":"Cripto","History":"Histórico","Reports":"Relatórios","Settings":"Configurações","Invite & sharing":"Convites e compartilhamento","Sign out":"Sair","Your business and life, in one orbit.":"Seus negócios e sua vida em um só lugar.","Search current view":"Pesquisar nesta página","Today Focus":"Foco de hoje","My Calendar":"Meu calendário","Connect Google Calendar":"Conectar Google Agenda","Sales pipeline":"Funil de vendas","Potential revenue":"Receita potencial","Project payments":"Pagamentos de projetos","Spending":"Despesas","This month":"Este mês","Investments":"Investimentos","Current value":"Valor atual","This month result":"Resultado deste mês","Last month result":"Resultado do mês passado","Six-month financial pulse":"Visão financeira de seis meses","Total projects":"Total de projetos","Total project value":"Valor total dos projetos","All projects":"Todos os projetos","Payment received":"Pagamento recebido","Awaiting payment":"Aguardando pagamento","Create project":"Criar projeto","Project name":"Nome do projeto","Client":"Cliente","Service":"Serviço","Status":"Status","Deadline":"Prazo","Project value":"Valor do projeto","Progress":"Progresso","Description":"Descrição","Notes":"Notas","Save changes":"Salvar alterações","Delete project":"Excluir projeto","Brief":"Briefing","Planning":"Planejamento","In progress":"Em andamento","Production":"Produção","Review":"Revisão","Delivered":"Entregue","On hold":"Pausado","Cancelled":"Cancelado","Find price":"Buscar preço","Use in purchase":"Usar na compra","Record purchase":"Registrar compra","Price paid":"Preço pago","Current price":"Preço atual","Quantity":"Quantidade","Asset name":"Nome do ativo","Consolidated holdings":"Ativos consolidados","Average price":"Preço médio","Total invested":"Total investido","Create":"Criar","Delete asset":"Excluir ativo","Adjust after sale":"Ajustar após venda","No assets in this portfolio.":"Nenhum ativo nesta carteira.","Save preferences":"Salvar preferências","Add":"Adicionar","Delete":"Excluir"},
es:{"Overview":"Resumen","Projects":"Proyectos","Expenses":"Gastos","Stocks":"Acciones","Settings":"Configuración","Save changes":"Guardar cambios","Delete project":"Eliminar proyecto","Payment received":"Pago recibido","Awaiting payment":"Esperando pago","Description":"Descripción","Notes":"Notas","Current price":"Precio actual","Use in purchase":"Usar en la compra"},
de:{"Overview":"Übersicht","Projects":"Projekte","Expenses":"Ausgaben","Stocks":"Aktien","Settings":"Einstellungen","Save changes":"Änderungen speichern","Delete project":"Projekt löschen","Payment received":"Zahlung erhalten","Awaiting payment":"Zahlung ausstehend","Description":"Beschreibung","Notes":"Notizen","Current price":"Aktueller Preis","Use in purchase":"Für Kauf verwenden"},
fr:{"Overview":"Vue d’ensemble","Projects":"Projets","Expenses":"Dépenses","Stocks":"Actions","Settings":"Paramètres","Save changes":"Enregistrer","Delete project":"Supprimer le projet","Payment received":"Paiement reçu","Awaiting payment":"Paiement en attente","Description":"Description","Notes":"Notes","Current price":"Prix actuel","Use in purchase":"Utiliser pour l’achat"},
it:{"Overview":"Panoramica","Projects":"Progetti","Expenses":"Spese","Stocks":"Azioni","Settings":"Impostazioni","Save changes":"Salva modifiche","Delete project":"Elimina progetto","Payment received":"Pagamento ricevuto","Awaiting payment":"In attesa di pagamento","Description":"Descrizione","Notes":"Note","Current price":"Prezzo attuale","Use in purchase":"Usa nell’acquisto"},
nl:{"Overview":"Overzicht","Projects":"Projecten","Expenses":"Uitgaven","Stocks":"Aandelen","Settings":"Instellingen","Save changes":"Wijzigingen opslaan","Delete project":"Project verwijderen","Payment received":"Betaling ontvangen","Awaiting payment":"Wacht op betaling","Description":"Beschrijving","Notes":"Notities","Current price":"Huidige prijs","Use in purchase":"Gebruiken bij aankoop"},
ja:{"Overview":"概要","Projects":"プロジェクト","Expenses":"支出","Stocks":"株式","Settings":"設定","Save changes":"変更を保存","Delete project":"プロジェクトを削除","Payment received":"入金済み","Awaiting payment":"入金待ち","Description":"説明","Notes":"メモ","Current price":"現在価格","Use in purchase":"購入に使用"},
ko:{"Overview":"개요","Projects":"프로젝트","Expenses":"지출","Stocks":"주식","Settings":"설정","Save changes":"변경 사항 저장","Delete project":"프로젝트 삭제","Payment received":"결제 완료","Awaiting payment":"결제 대기","Description":"설명","Notes":"메모","Current price":"현재 가격","Use in purchase":"구매에 사용"}}
Object.assign(dictionaries.pt,{"Client directory":"Diretório de clientes","Search clients":"Pesquisar clientes","No clients match this search.":"Nenhum cliente corresponde à pesquisa.","Add client":"Adicionar cliente","Name":"Nome","Company":"Empresa","Email":"E-mail","Phone":"Telefone","Last call date":"Data da última ligação","Active":"Ativo","Prospect":"Prospecto","Paused":"Pausado","Past":"Anterior","Client updated":"Cliente atualizado","Project costs":"Custos do projeto","Revenue minus project costs":"Receita menos custos do projeto","Discounted from project totals":"Descontado do total dos projetos","Net total":"Total líquido","Total project value":"Valor líquido dos projetos","Current portfolio value":"Valor atual da carteira","Market value":"Valor de mercado","Invested capital":"Capital investido","Unrealized return":"Retorno não realizado","Stock market value":"Valor das ações","Crypto market value":"Valor das criptomoedas","Find stock price":"Buscar preço de ação","Find crypto price":"Buscar preço de criptomoeda","Stock portfolios":"Carteiras de ações","Crypto portfolios":"Carteiras de criptomoedas","New portfolio name":"Nome da nova carteira","Symbol":"Símbolo","Finding…":"Buscando…","Record expense":"Registrar despesa","Spending list":"Lista de despesas","Expense name":"Nome da despesa","Amount":"Valor","Category":"Categoria","Subcategory":"Subcategoria","Conversion":"Conversão","Won":"Ganho","Lost":"Perdido","New":"Novo","Contacted":"Contatado","Qualified":"Qualificado","Proposal":"Proposta","Lead directory":"Diretório de leads","Add lead":"Adicionar lead","Tasks":"Tarefas","Follow-ups":"Acompanhamentos","Monthly list":"Lista mensal","Add grocery item":"Adicionar item","Reports":"Relatórios","Net tracked":"Saldo acompanhado","Available markets":"Mercados disponíveis","Country, language and currency":"País, idioma e moeda","Country / market":"País / mercado","Language":"Idioma","Default currency":"Moeda padrão"})
Object.assign(dictionaries.es,{"Clients":"Clientes","Leads Management":"Gestión de leads","Tasks & Follow-ups":"Tareas y seguimientos","Calendar":"Calendario","Pipeline":"Embudo","Projects":"Proyectos","Groceries":"Compras","Expenses":"Gastos","Stocks":"Acciones","Crypto":"Cripto","History":"Historial","Reports":"Informes","Invite & sharing":"Invitaciones y uso compartido","Client directory":"Directorio de clientes","Search clients":"Buscar clientes","Last call date":"Fecha de última llamada","Project costs":"Costes del proyecto","Total project value":"Valor neto de proyectos"})
Object.assign(dictionaries.de,{"Clients":"Kunden","Leads Management":"Lead-Verwaltung","Tasks & Follow-ups":"Aufgaben und Nachverfolgung","Calendar":"Kalender","Pipeline":"Pipeline","Projects":"Projekte","Groceries":"Lebensmittel","Expenses":"Ausgaben","Stocks":"Aktien","Crypto":"Krypto","History":"Verlauf","Reports":"Berichte","Invite & sharing":"Einladen und teilen","Client directory":"Kundenverzeichnis","Search clients":"Kunden suchen","Last call date":"Datum des letzten Anrufs","Project costs":"Projektkosten","Total project value":"Nettoprojektwert"})
Object.assign(dictionaries.fr,{"Clients":"Clients","Leads Management":"Gestion des prospects","Tasks & Follow-ups":"Tâches et suivis","Calendar":"Calendrier","Pipeline":"Pipeline","Projects":"Projets","Groceries":"Courses","Expenses":"Dépenses","Stocks":"Actions","Crypto":"Crypto","History":"Historique","Reports":"Rapports","Invite & sharing":"Invitations et partage","Client directory":"Répertoire clients","Search clients":"Rechercher des clients","Last call date":"Date du dernier appel","Project costs":"Coûts du projet","Total project value":"Valeur nette des projets"})
Object.assign(dictionaries.it,{"Clients":"Clienti","Leads Management":"Gestione lead","Tasks & Follow-ups":"Attività e follow-up","Calendar":"Calendario","Pipeline":"Pipeline","Projects":"Progetti","Groceries":"Spesa","Expenses":"Spese","Stocks":"Azioni","Crypto":"Cripto","History":"Cronologia","Reports":"Rapporti","Invite & sharing":"Inviti e condivisione","Client directory":"Elenco clienti","Search clients":"Cerca clienti","Last call date":"Data ultima chiamata","Project costs":"Costi del progetto","Total project value":"Valore netto dei progetti"})
Object.assign(dictionaries.nl,{"Clients":"Klanten","Leads Management":"Leadbeheer","Tasks & Follow-ups":"Taken en opvolging","Calendar":"Agenda","Pipeline":"Pipeline","Projects":"Projecten","Groceries":"Boodschappen","Expenses":"Uitgaven","Stocks":"Aandelen","Crypto":"Crypto","History":"Geschiedenis","Reports":"Rapporten","Invite & sharing":"Uitnodigen en delen","Client directory":"Klantenlijst","Search clients":"Klanten zoeken","Last call date":"Datum laatste gesprek","Project costs":"Projectkosten","Total project value":"Netto projectwaarde"})
Object.assign(dictionaries.ja,{"Clients":"顧客","Leads Management":"リード管理","Tasks & Follow-ups":"タスクとフォローアップ","Calendar":"カレンダー","Pipeline":"パイプライン","Projects":"プロジェクト","Groceries":"食料品","Expenses":"支出","Stocks":"株式","Crypto":"暗号資産","History":"履歴","Reports":"レポート","Invite & sharing":"招待と共有","Client directory":"顧客一覧","Search clients":"顧客を検索","Last call date":"最終通話日","Project costs":"プロジェクト費用","Total project value":"プロジェクト純額"})
Object.assign(dictionaries.ko,{"Clients":"고객","Leads Management":"리드 관리","Tasks & Follow-ups":"작업 및 후속 조치","Calendar":"캘린더","Pipeline":"파이프라인","Projects":"프로젝트","Groceries":"장보기","Expenses":"지출","Stocks":"주식","Crypto":"암호화폐","History":"기록","Reports":"보고서","Invite & sharing":"초대 및 공유","Client directory":"고객 디렉터리","Search clients":"고객 검색","Last call date":"마지막 통화 날짜","Project costs":"프로젝트 비용","Total project value":"프로젝트 순가치"})
Object.assign(dictionaries.pt,{"Client":"Cliente","Active leads":"Leads ativos","Estimated potential":"Potencial estimado","Active leads only":"Apenas leads ativos","Client history":"Histórico de clientes","Converted leads retained":"Leads convertidos mantidos","Converted clients":"Clientes convertidos","Lost":"Perdido","spaces available":"vagas disponíveis"})
Object.assign(dictionaries.es,{"Client":"Cliente","Active leads":"Leads activos","Estimated potential":"Potencial estimado","Client history":"Historial de clientes","Lost":"Perdido"})
Object.assign(dictionaries.de,{"Client":"Kunde","Active leads":"Aktive Leads","Estimated potential":"Geschätztes Potenzial","Client history":"Kundenverlauf","Lost":"Verloren"})
Object.assign(dictionaries.fr,{"Client":"Client","Active leads":"Prospects actifs","Estimated potential":"Potentiel estimé","Client history":"Historique clients","Lost":"Perdu"})
Object.assign(dictionaries.it,{"Client":"Cliente","Active leads":"Lead attivi","Estimated potential":"Potenziale stimato","Client history":"Cronologia clienti","Lost":"Perso"})
Object.assign(dictionaries.nl,{"Client":"Klant","Active leads":"Actieve leads","Estimated potential":"Geschat potentieel","Client history":"Klantgeschiedenis","Lost":"Verloren"})
Object.assign(dictionaries.ja,{"Client":"顧客","Active leads":"アクティブなリード","Estimated potential":"見込み額","Client history":"顧客履歴","Lost":"失注"})
Object.assign(dictionaries.ko,{"Client":"고객","Active leads":"활성 리드","Estimated potential":"예상 잠재 가치","Client history":"고객 기록","Lost":"실패"})
Object.assign(dictionaries.pt,{"Payment name":"Nome do pagamento","Client (optional)":"Cliente (opcional)","Amount received":"Valor recebido","Original currency":"Moeda original","Received date":"Data de recebimento","Method":"Método","Reference / invoice (optional)":"Referência / fatura (opcional)","Notes (optional)":"Notas (opcional)","+ Add payment":"+ Adicionar pagamento","Add payment":"Adicionar pagamento","Edit payment":"Editar pagamento","Delete payment":"Excluir pagamento","Save payment":"Salvar pagamento","Cancel":"Cancelar","Saving…":"Salvando…","Deleting…":"Excluindo…"})
Object.assign(dictionaries.pt,{"Archive lead":"Arquivar lead","Delete lead":"Excluir lead"})
Object.assign(dictionaries.pt,{"Payment status":"Status do pagamento","Payment date (received / expected)":"Data do pagamento (recebido / previsto)"})
Object.assign(dictionaries.pt,{"Filter by status":"Filtrar por status","All statuses":"Todos os status","Payment month":"Mês do pagamento","Client name":"Nome do cliente","Search client name":"Pesquisar nome do cliente","Search payment name":"Pesquisar nome do pagamento","Payment date order":"Ordem por data de pagamento","Newest first":"Mais recentes primeiro","Oldest first":"Mais antigos primeiro","Clear filters":"Limpar filtros","No payments match these filters.":"Nenhum pagamento corresponde aos filtros.","Filters affect this list only. Month uses the received or expected payment date.":"Os filtros afetam apenas esta lista. O mês usa a data de recebimento ou a data prevista do pagamento."})
Object.assign(dictionaries.pt,{"Total payments received":"Total de pagamentos recebidos","Past 12 calendar months · including this month":"Últimos 12 meses · incluindo este mês","Import Excel":"Importar Excel","Import clients":"Importar clientes","Confirm import":"Confirmar importação","Processing…":"Processando…","Importing…":"Importando…"})
type TranslationState={source:string;rendered:string}
const originals=new WeakMap<Node,TranslationState>(),placeholders=new WeakMap<HTMLInputElement|HTMLTextAreaElement,TranslationState>()
export function translateUpdatedText(current:string,previous:TranslationState|undefined,dictionary?:D):TranslationState{
  // React owns changing values. Only reuse a source when our own translation is still displayed.
  const source=previous&&current===previous.rendered?previous.source:current
  const key=source.trim(),value=dictionary?.[key]
  return {source,rendered:value?source.replace(key,value):source}
}
export function WebsiteTranslator({language="en"}:{language?:string}){
  useEffect(()=>{
    const root=document.querySelector(".wealth-dashboard");if(!root)return
    const dictionary=dictionaries[language]
    const observer=new MutationObserver(translate)
    function translate(){
      observer.disconnect()
      try{
        const walker=document.createTreeWalker(root!,NodeFilter.SHOW_TEXT);let node:Node|null
        while((node=walker.nextNode())){
          const state=translateUpdatedText(node.textContent||"",originals.get(node),dictionary)
          originals.set(node,state)
          if(node.textContent!==state.rendered)node.textContent=state.rendered
        }
        root!.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>("input[placeholder],textarea[placeholder]").forEach(el=>{
          const state=translateUpdatedText(el.placeholder,placeholders.get(el),dictionary)
          placeholders.set(el,state)
          if(el.placeholder!==state.rendered)el.placeholder=state.rendered
        })
        document.documentElement.lang=language
      }finally{observer.observe(root!,{childList:true,characterData:true,subtree:true,attributes:true,attributeFilter:["placeholder"]})}
    }
    translate()
    return()=>observer.disconnect()
  },[language])
  return null
}

