import type { Metadata } from "next"
import { LegalPage } from "@/components/legal-page"

export const metadata: Metadata = {
  title: "Terms of Service | Orbit LM",
  description: "Terms for using Orbit-LM accounts, subscriptions, workspaces and connected services.",
  alternates: { canonical: "https://orbit-lm.com/terms-of-service" },
}

export default function TermsOfService() {
  return <LegalPage title="Terms of Service" intro="These terms describe the conditions for using Orbit-LM’s website and workspace tools. Please read them alongside our Privacy Policy and the terms shown at checkout." sections={[
    { title: "Using Orbit-LM", content: <p>Orbit-LM provides tools for organizing business and personal information. By using the service, you agree to these terms. You must have the legal capacity to enter this agreement. If you act for a business, you must be authorized to bind it. Contact us at <a href="mailto:tsblsestudio@gmail.com">tsblsestudio@gmail.com</a> with questions.</p> },
    { title: "Accounts and shared access", content: <p>Provide accurate account details, keep your credentials secure and notify us of suspected unauthorized access. You are responsible for actions you authorize through your account and for the permissions you grant to invited users. Each person should use their own credentials. Workspace owners are responsible for managing their team’s access and the information shared with it.</p> },
    { title: "Plans, payments and cancellation", content: <p>Available features and usage limits depend on your plan. The price, currency, taxes, billing interval, renewal conditions and any additional charges shown at checkout govern your purchase. A recurring subscription renews under those disclosed conditions until canceled. Follow the cancellation instructions in your purchase confirmation or billing provider account, or contact us for help. Refunds are subject to the applicable checkout terms and mandatory consumer rights; nothing here removes rights provided by law. A separate written agreement may define the scope and support included in business customization services.</p> },
    { title: "Your records and responsibilities", content: <p>You retain your rights in the content you provide. You give Orbit-LM permission to host, process and transmit that content as needed to operate the features you use. You must have the right to upload client or team information, logos and other materials, and obtain any legally required notices or permissions. Keep independent copies of important records and check data accuracy before relying on a report, invoice or message.</p> },
    { title: "Invoices and automations", content: <p>When you configure billing dates, recurring charges, reminders or invoice delivery, you authorize the corresponding automated actions. Check recipients, amounts, dates, frequency, descriptions and branding before enabling or using them. Delivery depends on email providers and recipient systems; a sent status is not proof that a recipient read the message or paid. Orbit’s invoice and reporting tools do not determine tax compliance, collect your clients’ debts or replace professional accounting advice.</p> },
    { title: "Investments, health and automated assistance", content: <p>Market prices, conversions, calorie estimates and automated support responses may be delayed, incomplete or inaccurate. Orbit is an organizational tool, not a broker, medical provider or financial adviser. Recording an investment does not execute a market trade. Do not treat outputs as personalized investment, medical, legal or tax advice. Verify important decisions with appropriate independent sources or qualified professionals.</p> },
    { title: "Connected services", content: <p>Optional integrations, market-data sources, email services and payment providers have their own terms and availability. You control which available connections you authorize. Changes, rate limits, outages or revoked permissions may affect connected features. Disconnecting an integration does not necessarily delete information previously saved in Orbit or the other service.</p> },
    { title: "Acceptable use", content: <p>Do not use Orbit for unlawful activity, spam, harassment, infringement, unauthorized collection of personal information or distribution of malicious content. Do not attempt to bypass plan limits or security controls, access another workspace without permission, disrupt the service or misuse connected providers. We may restrict access when reasonably necessary to address abuse, nonpayment or security risks, with notice where appropriate and permitted.</p> },
    { title: "Availability, changes and ending access", content: <p>We work to maintain and improve Orbit, but uninterrupted or error-free operation is not guaranteed. Features may change, with notice where required for material changes affecting your subscription. You may stop using the service and request account deletion by contacting us; also cancel recurring billing through the applicable cancellation process. Data retention and deletion are described in the <a href="/privacy-policy">Privacy Policy</a>. Export important records before ending access.</p> },
    { title: "Intellectual property and legal protections", content: <p>Orbit-LM’s software, design and branding remain the property of their respective rights holders. Access to the service does not transfer those rights. To the extent permitted by applicable law, the service is provided without guarantees beyond those expressly agreed. Nothing in these terms excludes liability or consumer protections that cannot lawfully be excluded. Any dispute remains subject to applicable law and any mandatory rights to use competent courts or consumer authorities.</p> },
    { title: "Updates and contact", content: <p>We may revise these terms and will update the date above. Material changes will be communicated where required; any consent required by law will be requested. For billing, service or legal questions, email <a href="mailto:tsblsestudio@gmail.com">tsblsestudio@gmail.com</a>.</p> },
  ]}/>
}
